### ISSUE TITLE
Alternative way to connect directly browser js-waku to nim-waku

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#107]
## Problem

If https://github.com/status-im/nim-waku/issues/434 is not yet done then we need to consider alternative ways to connect js-waku browser to nim-waky to achieve #68.

## Solutions

- long polling over https
- QUIC

**Comment by D4nte** [comment]
Cc @oskarth do you think we still need to investigate? Or can we close once https://github.com/status-im/infra-nim-waku/issues/6 is done?

**Comment by oskarth** [comment]
Can probably hold off on this and then close or leave open for general discussion, e.g. native nim-ws/quic etc support. Up to you

**Comment by fryorcraken** [comment]
(secure) websocket support implemented in nwaku.
