### ISSUE TITLE
Pre-commit hook to check code format

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#110]
# Problem

The CI includes formatting check, best if the developer knows that his code need formatting while commiting instead of when the CI is running

# Solution

git pre-commit hooks do not play nice when the change files. Instead, they should just run the format checks (and spelling).

# Considerations

- Format checks should be run in both root folder and examples folder (web-chat)
- There are several scripts for those (`prettier`, `lint`, `spelling`), it may be worth grouping in the package.json under one script (`"test:format": "run-s lint prettier spelling"`).

**Comment by fryorcraken** [comment]
Using husky and lint-staged
