### ISSUE TITLE
Define recommendations for usage of topics 

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#114]
As a developer I want some idea on what `pubsubTopic` or `contentTopic` I should use or, if I have to create my own, how to format it.

**Comment by oskarth** [comment]
https://github.com/status-im/js-waku/pull/111#discussion_r624899194

**Comment by D4nte** [comment]
Tracked with https://github.com/vacp2p/rfc/issues/364

**Comment by D4nte** [comment]
Done
