### ISSUE TITLE
waku relay API: auto-subscribe

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#17]
## Problem

Currently, developer always need to do a call to `WakuRelay.subscribe()` to use waku relay.

## Solution

Similarly to nim-waku, an auto-subscribe to the default topic can make the API easier to use as the developer would have one less call to do.

**Comment by D4nte** [comment]
Let's wait until https://github.com/status-im/nim-waku/issues/445 is resolved before trying to tackle this one as we know of some timing issues and there would be little value if we have various `sleep` in the library to allow for a resilient auto-subscribe.

**Comment by oskarth** [comment]
This is an issue more for library design, is that correct? In terms of making it ergonomic and having to setup fewer things for the default behavior.

**Comment by D4nte** [comment]
yes correct, I use the label 'API' to flag anything which is more about the API itself, the dev ex using it and any issue/improvements that can be done on its current design.

This is low priority as the focus is to get the chat app to support waku store first.
