### ISSUE TITLE
queryHistory should make storePeerId an optional parameter

### ISSUE THREAD

**Issue by bgits** [status-im/js-waku#184]
- **I'm submitting a ...**
  [ ] bug report
  [] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
According to the documentation, in order to fetch messages the `queryHistory` function requires a `storePeerId`. This brings up several issues. The first is it's not clear how to get the available Peer-ids and the second is that unless the application has a reason to query a specific node it creates extra boilerplate. Making this an optional parameter and selecting a peerId at random seems like a sensible option.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by D4nte** [comment]
At this stage, selecting a pseudo-random node sounds reasonable.
As we see [Waku v2 Fault-Tolerant Store](https://rfc.vac.dev/spec/21/) evolve then a random should become sufficient.

Note that once https://github.com/vacp2p/rfc/discussions/374 is in place then the library can select the right node depending on the query.

**Comment by D4nte** [comment]
same should be done for light push protocol
