### ISSUE TITLE
Remove ChatMessage for js-waku

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#194]
## Problem

`ChatMessage` is part of the toy-chat application protocol. It is included in js-waku as it is convenient to share code between cli-chat and web-chat examples. However, we have seen projects using this class outside of the toy-chat protocol context instead of defining their own protobuf messages.
To avoid making `ChatMessage` some sort of de facto standard, we should move it out of js-waku

## Solution

Remove `ChatMessage` from js-waku, redefine it in the examples or it's own toy-chat package.

**Comment by bitsikka** [comment]
Cool
This sort of thing will help App devs get a clearer mental model of how their App should be structured. This only started to become apparent to me after going through the hackathon and having had some knowledge of how Status-react is structured.

Currently, in my mind Status-react is the reference structure. I may still be incorrect but in it, there seems to be 3 layers:
1) - Waku nodes (nim-waku, js-waku, go-waku)
2) - Status-go (local backend in the client)
3) - Ui Client

I imagine ChatMessage would be defined in #2 built upon #1 primitives and consumed by #3. That's how I see it.

It would definitely be cool to extract a generalized structure/model for App devs in the explanations. 👍🏽

**Comment by D4nte** [comment]
Hi @bitsikka,

Thank you for your input. Yes, I agree with you.

js-waku intends to provide the base layer, building blocks, to allow DApp to use the Waku network.
Which means that `ChatMessage` does not really belong here.

I also agree with you that Status chat data structures, encryption, etc, belongs in status-go.
It would be interesting if one day we can provide a JS library that allows other apps to bridge to Status's community rooms and chat. This is something we keep in the back of our head but the priority is to get go-waku integrated in status-go.

Finally, do note that `ChatMessage` is the data structure for [TOY-CHAT](https://rfc.vac.dev/spec/22/). It is here to allow us to build examples of Waku DApps and also do some dogfooding of the Waku Network.

Ultimately, we expect `ChatMessage` to go away (or remain for example purposes only).
