### ISSUE TITLE
Poll/Vote White Label Solutions

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#257]
# Problem

Gas-less Polling and Gas Efficient voting are possible use cases that leverage the Waku network capabilities.

We want to allow dApp developers to easily add said features to their dApps.
By _easily_, we mean:
- Easy access: minimize the API and concepts to learn
- Fast deployment: minimize the LOC to write

# Solution

Create white label solutions that allows dApp developers to integrate these features.

# Feature definition

The features share a similar design to those made for the Status Community Directory Curation dApp.

## Gas-less Polling

See _Featured Communities_: https://github.com/vacp2p/rfc/pull/432

This feature allows a poll author to cast a poll, users to respond and view results of the poll.
This poll does not interact with any blockchain.

For now, the white label solution should share similar properties than the _Feature Communities_,
it can be mode more generic in the future if dApp developers request it.
The only addition is to be able to cast a "time limited" poll in addition _Featured Community_-style "ongoing" polls.

Requirements:
- Users are token holder of a given ERC-20 token.
- Users responses can be weighted or non-weighted.
- Polls can either be _ongoing_ or _time limited_

Hence, the expected inputs of a poll are:

- ERC-20 Token contract to ensure polled users are token holders
- Poll id: to ensure responses only count for a given poll.
- Ongoing or Time limited

## Ongoing polls

This is similar to the _featured communities_ mechanism.
The example values in bracket are those used for the _featured communities_.

Additional inputs are:
- Oldest response: How old can poll responses be (e.g. 4 weeks)
- Function to retrieve valid answers (e.g. check blockchain contract for communities' public keys)
- Result window (e.g. one week)
- Start of result window (e.g. Sunday 23:59:59 UTC)
- Rolling result: whether a winner can win 2 times in a row (e.g. false)

## Time limited polls

In anticipation of a simpler, social media style, polls, we should offer a time limited poll.

Additional inputs are:
- List of valid answers
- Start of poll
- End of poll

A message is sent to start the poll, the message contains:
- poll end time
- possible answers
- poll id

Poll start message uses dedicated content topic

Only show polls that started less than 3 weeks go and ended less than 2 weeks ago.

## Gas-efficient voting

See _Community Curation Directory Voting_: https://rfc.vac.dev/spec/24/

This voting method is characterized the fact that the vote author spends most gas whereas most participants do not spend any gas.

1. The author deploys a contract on-chain
2. Votes cast votes over waku
3. Author aggregates votes and commit them on chain
4. A user can decides to also aggregates votes and commit them on chain if they disagree with the author's result.

Requirements:
- Voters are token holder of a given ERC-20 token.
- Votes are weighted: a user can decide the number a tokens that backs a vote (no spending)
- Voting period is time limited

Inputs:
- ERC-20 Token contract address to use
- Vote id, to ensure responses only count for a given vote
- Valid answers
- End time

# Deliverables

For each white label solutions, the deliverable should be in 2 parts:

1. A codebase that can be used as an npm package by dApp developers that matches the requirements stated above + React components package
2. An example UI that demonstrates how this package can be used
3. An RFC that describes the behaviour

# Note

Note that these solutions must in line with the recommended usage of Waku:
- Usage of protobuf https://rfc.vac.dev/spec/10/
- Follow recommendation for content topics: https://rfc.vac.dev/spec/23/

**Comment by D4nte** [comment]
# Minutes of 4 Aug meeting

## Attendees

- @Szymx95 (EthWorks)
- Kuba (EthWorks)
- @D4nte (Status/Vac)

## Minutes

- Only token holder of the specified contract can start a poll or vote
- For ongoing polls, we assume there is no start or end that it's an ongoing feature for a given dApp.
- For the time limited polls, we will need to send a start message that contains the poll parameters:
  - ~Start time~ Receiving the message can be used as a start time
  - End time
  - Possible answers (static list in the message)
  - Poll id
 Poll start messages should be send on a different content topic than poll answers.
- Let's use an iterative approach and we can work the API and make it more flexible over time.
- In terms of deliverables, Szymon propose to also deliver a React components package so that users can import said react components. The example UI will use this React components package
- For the poll example UI:
  - Only do limited time example UI
  - For the poll UI, the dAPP would retrieve polls and answer from Waku store and then display polls in a list with most recent poll on top
    - If the poll is unanswered, let the user answer and then it shows current result
    - If an own answer is retrieved from the store, then direct show result
    - If the poll is ended, then also directly show result
  - Only show votes that ended less than 2 weeks ago and started less than 3 weeks ago. Store nodes only store messages for 30 days. We want to avoid weird behaviour where the result changes because some older answered are shown
Time limited
 - Protobuf should be used instead of JSON, see guide: https://github.com/status-im/js-waku/blob/main/guides/relay-receive-send-messages.md#use-protobuf

## Action items

- [x] @D4nte to send guides to Szymon
- [ ] @D4nte to update description as per minutes.
- [ ] @Szymx95 to organize follow-up meeting Wednesday 13 Aug.

**Comment by D4nte** [comment]
For the poll, let's keep a non-weighted voting please. This is matches more a standard use case of Twitter-like polls.

**Comment by Szymx95** [comment]
We could implement both weighted and non-weighted polls.

**Comment by D4nte** [comment]
> We could implement both weighted and non-weighted polls.

Sounds good, let's start simple as you suggested in the call.

**Comment by D4nte** [comment]
# Minutes Thursday 19 August Meeting

## Attendees

- @D4nte 
- @Szymx95 

## Minutes

- poll end time added
- EIP-712 sign typed data is used. Only `eth_signTypedData_v3` seems available on desktop, mobile has v3 (not sure about v4) -> see Action Item
- Keep API separate for polling and voting.
- Need time window for store query: @D4nte already working on it https://github.com/status-im/js-waku/pull/271
- Will use styling that kuba prepared

## Action Items

- [ ] @D4nte follow-up on availability of `eth_signTypedData_v4` on mobile and desktop.
- [ ] @Szymx95 to provide documentation on smart contract behaviour to prepare for audit by Status Security team (see https://our.status.im/what-is-a-security-audit-when-you-should-get-one-and-how-to-prepare/)
- [ ] @D4nte to ping @Szymx95 once time-window queried are merged in js-waku (and again when released)

**Comment by D4nte** [comment]
`eth_signTypedData_v4` could be available on desktop but not really the priority.

**Comment by D4nte** [comment]
# Minutes Thursday 19 August Meeting

## Attendees

- @D4nte 
- @Szymx95 

## Minutes

- `startTime` and `endTime` must be passed for time filtering
- use v3 for sign typed data: Status desktop does not support v4. v4 bring array of arrays that we do not need.
- One common package for both dApps, but use separate classes for polling and voting
- Use non-weighted poll for code examples
- README can document API clearly (eg explains how to use weighted polls).
- Design is yet to be responsive (tbd)
- Layout is part of the react components: still some work to be done for the react components.
- Started smart contract, not yet finished. 

## Next week
- finish smart contract + prepare for audit
- use v3 for sign typed data
- make ui responsive
- Make it easier to use the react component 

## Action items

- [ ] @D4nte to let Kuba know about DappConnect logo to put in the white label dApp
- [ ] @Szymx95 to provide documentation on smart contract behaviour to prepare for audit by Status Security team (see https://our.status.im/what-is-a-security-audit-when-you-should-get-one-and-how-to-prepare/) (from last week).

**Comment by D4nte** [comment]
# Minutes Wednesday 1 September Meeting

# Attendees

- @D4nte 
- @Szymx95 

# Minutes

- Did smart contract and readme doc: https://github.com/EthWorks/status-waku-voting/blob/master/packages/contracts/README.md
- Issues when using bootstrap API, `await` from `Waku.create` does not wait until connected to a store node.
- Used EIP-712 for Status Community Curation dApp: Status Desktop display of data to sign is not pretty (still better than eth personal sign).
- Some issues with getting dupe messages when only relying on waku store: Use waku relay for live message and waku store only when starting the dApp.
- UI is now responsive
- Szymon is Away Wednesday - Friday next week

# Action items
- [ ] @D4nte to update API/Doc to make it easier to use waku store just after creating waku instance
- [ ] @D4nte to follow with status desktop to improve display of data to sign
- [ ] @Szymx95 to use waku relay to receive live messages instead of waku store

**Comment by D4nte** [comment]
# Minutes Wednesday 15 September

## Attendees

- @D4nte
- @Szymx95 

## Minutes
- @D4nte wrote [security considerations](https://github.com/status-im/dappconnect-voting-sdk#security-considerations) for the voting SDK.
  - [ ] @Szymx95 had some feedback and will review in more details and confirm dApp behavior.
  - [ ] Once done, we can ask Status security team to review.
- [ ] @Szymx95 to do some final touches:
  - Refactor some code under a general class to avoid code duplication, especially around usage of js-waku.
  - Page the retrieval of `voting rooms` from smart contract
- Once, done, @Szymx95 will move the code to https://github.com/status-in/dappconnect-voting-sdk.
- @D4nte will then play with it, create some voting/polling dApp, ask questions, write guides and when all good, publish the packages in npm
- Issues encountered with websocket connection on the prod fleet
  - This is due to another project taking too many resources.
  - We asked them to run their own node
  - [ ] @D4nte to update js-waku to not be too eager on node connection
  - In the future, we will encourage dApp dev to run their own node to help with this, at least until incentivization is ready.
  - Work to make deploying `wakunode2` with websocket easier is in progress https://github.com/status-im/nim-waku/issues/434

### Chat SDK

@D4nte will mainly need help for React hooks, components and UI for the DappConnect Chat SDK: https://github.com/status-im/dappconnect-chat-sdk/issues/1

@Szymx95 is best suited to help with the React hooks.
Maria will then handle react components and UI.

**Comment by D4nte** [comment]
When publishing work, be sure to record a video.

**Comment by D4nte** [comment]
Done, doc published.
