### ISSUE TITLE
Uncaught (in promise) TypeError: Class constructor Gossipsub cannot be invoked without 'new'

### ISSUE THREAD

**Issue by TheBojda** [status-im/js-waku#323]
## Problem

I've installed waku through npm (npm install js-waku), and the below minimal js throws the "Uncaught (in promise) TypeError: Class constructor Gossipsub cannot be invoked without 'new'" error.

This is my JS file:
import 'regenerator-runtime/runtime'
import { Waku } from "js-waku";

async function init() {
  await Waku.create({ bootstrap: true });
}
	
init();

**Comment by TheBojda** [comment]
I've downloaded min-js-web-chat and changed the js-waku dependency: 
```
"js-waku": "../../build/main" ->  "js-waku": "^0.14.1"
```
It throws the same error. So, something is wrong with the package in the npm registry, not a Parcel related problem. You should publish it a different way or something. :)

Until it, I can use 0.13.1.

**Comment by D4nte** [comment]
> 

Thank you for the investigation. Will review.

**Comment by D4nte** [comment]
@TheBojda can you let me know if 0.14.2-rc.0 fixes the issue? thanks!

**Comment by TheBojda** [comment]
Yay. Works like a charm. Ty :)

**Comment by D4nte** [comment]
Excellent, now released with 0.14.2.
