### ISSUE TITLE
How to send a file

### ISSUE THREAD

**Issue by xyy0725** [status-im/js-waku#326]
How does JS-waku send image files with custom messages?

I convert the image to Uint8Array format and combine it with custom messages into strings.

Finally, 'waku.relay. Send' is used to send it.

However, it becomes invalid when it exceeds 100KB.

What should I do

      async sendImages(){
        let el = document.getElementById('file')
        let _this = this
        const file = el.files[0]
        const reader = new FileReader();
        reader.readAsArrayBuffer(file);   
        reader.onload = function () {
          let un8 = new Uint8Array(this.result)
          let tempData = {
            formAddress: _this.id,
            messageType: 2,
            imgType: file.type,
            message: un8
          }
          let data = Buffer.from(JSON.stringify(tempData), 'utf-8');
          window.jswaku.WakuMessage.fromBytes(
            data,
            ChatContentTopic,
          ).then(wakuMsg=>{
            _this.waku.relay.send(wakuMsg).then(()=>{
              console.log('success!')
            }).catch((e)=>{
              console.error(e)
            })
          })
        }
      }

**Comment by D4nte** [comment]
Thank you for your patience.

Waku is not really design to support large files.

However, we have recently increased the max message size of messages over Waku Relay from 64kb (hence the 100kb limit you are seeing). I will review the new size limit and implementation status and revert back to you.

**Comment by D4nte** [comment]
It should now be possible to send messages up to 1MB on the prod and test networks: https://github.com/status-im/nim-waku/issues/739#issuecomment-979771854

Please close the issue if resolved or let me know if not.

**Comment by xyy0725** [comment]
Thank you for your reply. I will verify it
