### ISSUE TITLE
Uncaught Error: crypto and/or subtle api unavailable

### ISSUE THREAD

**Issue by xyy0725** [status-im/js-waku#345]
"js-waku": "^0.14.2",
    Chrome
    node: '14.17.6'
    TS: 4.1.6

Why is an error reported when using 'Js-waku' which is normal in the local environment and placed on the server。
![微信图片_20211209155641](https://user-images.githubusercontent.com/26158407/145356508-084ba6ec-4d64-4f21-ade1-e9f80f0265b9.png)

ERROR:   

browser.js:85 Uncaught Error: crypto and/or subtle api unavailable
    at Object.<anonymous> (browser.js:85)
    at Object.55a5 (chunk-vendors.41f6647e.js:31)
    at i (bootstrap:84)
    at Object.7772 (version_1.js:1)
    at i (bootstrap:84)
    at Object.241b (index.js:1)
    at i (bootstrap:84)
    at Object.d7f7 (waku.js:1)
    at i (bootstrap:84)
    at Object.f654 (chunk-vendors.41f6647e.js:43)

**Comment by D4nte** [comment]
What browser are you using? The subtle crypto API is available in most modern browsers: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

**Comment by xyy0725** [comment]
> What browser are you using? The subtle crypto API is available in most modern browsers: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto

browser:   Google Chrome  -v 93.0.4577.63

**Comment by D4nte** [comment]
How do you bundle your app?

**Comment by xyy0725** [comment]
> How do you bundle your app?
> Please share conf files.

I did it by accessing the domain name directly

**Comment by D4nte** [comment]
> > How do you bundle your app?
> > Please share conf files.
> 
> I did it by accessing the domain name directly

Sorry i don't understand. Do you use webpack? A web framework? React? Angular?

**Comment by xyy0725** [comment]
> > > How do you bundle your app?
> > > Please share conf files.
> > 
> > 
> > I did it by accessing the domain name directly
> 
> Sorry i don't understand. Do you use webpack? A web framework? React? Angular?

The same error occurs when I package the 'Waku V2 Chat app' and mount it to my domain

**Comment by xyy0725** [comment]
> > > > How do you bundle your app?
> > > > Please share conf files.
> > > 
> > > 
> > > I did it by accessing the domain name directly
> > 
> > 
> > Sorry i don't understand. Do you use webpack? A web framework? React? Angular?
> 
> The same error occurs when I package the 'Waku V2 Chat app' and mount it to my domain

webpakc

**Comment by D4nte** [comment]
You must use https to access your webapp to enable subtle crypto.

**Comment by xyy0725** [comment]
> You must use https to access your webapp to enable subtle crypto.

OMG.... My current test domain name is not HTTPS..

I'm going to try it now and THANK you so much for your help

**Comment by xyy0725** [comment]
> You must use https to access your webapp to enable subtle crypto.

It worked. Thank you again
