### ISSUE TITLE
Improved topic management

### ISSUE THREAD

**Issue by TheBojda** [status-im/js-waku#348]
This is an idea, how waku could make topic management much more efficient.

## Problem

When I send a message to a topic, now waku broadcasts it to the default topic (/waku/2/default-waku/proto), every node gets and forwards the message through the gossipsub mesh, and the subscribed nodes process it. This method is inefficient because if there are 1000 nodes, and only 3 nodes are subscribed to the 'test' topic, all the 1000 nodes will get the message instead of the 3 subscribed nodes.

## Proposed Solutions

My solution to solve this problem is a simple discovery protocol. I would reserve the default topic only for node discovery. When a node subscribes to a topic, it sends a discovery message that is broadcasted in the network. The discovery message contains the topic and the requestor node address. If a node is also subscribed to the topic, it sends back its address to the requestor node. The requestor node adds the address to its address book and builds a separated gossipsub mash for the new 'native' libp2p topic. When it sends a message to the topic, it uses this 'native' topic and its gossipsub mesh that contains only the other subscribed peers.

Example: There are 1000 nodes in the waku mesh, that are subscribed to the default topic, and 3 nodes are subscribed to the 'test' waku topic. When a new, 4. node wants to subscribe to the 'test' topic, it sends a discover message to the default topic, and the other 3 nodes answer back their addresses. The 4. node add these addresses to its address book, and subscribes to the 'test' topic through libp2p. Everything will be done by libp2p gossipsub, the separated gossipsub mash will be built by it. When this 4. node sends a message to the 'test' topic. Only the other 3 nodes will get it which saves much bandwidth.

**Comment by D4nte** [comment]
This is a protocol issue/discussion and not specifically related to the js-waku implementation. Moved to https://github.com/vacp2p/rfc/issues/477.
