### ISSUE TITLE
Publish API doc on js-waku.wakuconnect.dev

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#355]
Automatically publish the doc generated via typedoc (`npm run doc:html`) on js-waku.wakuconnect.dev:
- When pushing on `main` branch
- At release time

**Comment by D4nte** [comment]
@jakubgs I setup a GitHub action to do publish a number of items on the GitHub Pages: https://github.com/status-im/js-waku/blob/main/.github/workflows/deploy-gh-pages.yml

I'd like to start cleaning this up by moving the generated documentation to js-waku.wakuconnect.dev as you previously suggested.

The idea setup would be to have access to the documentation for:
- main branch (e.g. https://js-waku.wakuconnect.dev/main)
- latest release (e.g. https://js-waku.wakuconnect.dev/latest redirect/hosts doc for 0.14.2)
- previous given releases (e.g. https://js-waku.wakuconnect.dev/0.14.1, etc)

The documentation is generated using `typedoc`: `npm run doc:html`.

Let me know your thoughts, what is feasible and what I need to do/research to achieve this.
Thanks!

**Comment by jakubgs** [comment]
It's not going to be easy to have multiple versions. This kind of thing requires:

* Building of previous versions (every time, or continuously and saving results)
* Some kind of main page that's separate form the docs themselves
* Some way to manage which version is "latest"

I've never use TypeDoc, so I have no idea if it can handle multiple versions, but from a brief docs skim I can't see it. So it would require some kind of custom setup to combine multiple versions under a single page, which is not trivial.

Also, why does this repo use `main` instead of `master` like pretty much every single other repo in `status-im` org? Inconsistent.

**Comment by D4nte** [comment]
> So it would require some kind of custom setup to combine multiple versions under a single page, which is not trivial.

I think it would be reasonable to start by only building/publishing latest `main` HEAD documentation as a first step.
We can then review the handling of multiple versions at a later stage once the library is widely used and users want it.

> Also, why does this repo use `main` instead of `master` like pretty much every single other repo in `status-im` org? Inconsistent.

I think it was a default setting in GitHub. I'll align with the other repos.

**Comment by jakubgs** [comment]
>We can then review the handling of multiple versions at a later stage once the library is widely used and users want it.

Sure, I can get this going with the current domain, and then we can switch to `wakuconnect.dev` once it's migrated.

**Comment by D4nte** [comment]
Up to you, I don't mind if you wait for the new domain. Thanks!

**Comment by jakubgs** [comment]
Actually, I found out that Corey bought the domain using our NameCheap account which I have access to:

![image](https://user-images.githubusercontent.com/2212681/148287606-fe36fd88-a347-4876-92ce-d9cd31045f83.png)

So that simplifies this.

**Comment by D4nte** [comment]
Done with #410

**Comment by jakubgs** [comment]
Examples are now available under:

* https://js-waku.wakuconnect.dev/examples/web-chat/
* https://js-waku.wakuconnect.dev/examples/eth-pm/
* https://js-waku.wakuconnect.dev/examples/eth-pm-wallet-encryption/
