### ISSUE TITLE
Bug: Cannot convert BigInt value to a number.

### ISSUE THREAD

**Issue by ritvij14** [status-im/js-waku#358]
This is a **bug report**

## Problem

In our frontend platform at Huddle01 we are facing this bug on running `yarn build`.
<img width="1065" alt="Screenshot 2021-12-21 at 3 20 50 PM" src="https://user-images.githubusercontent.com/51456744/147234505-1a15e96b-bd13-4c2a-a326-5c8fd5f2f953.png">

On checking various packages we found that when we commented the usage of waku functions and deleted the waku package then this error wasn't showing up.

Here is all the code related to waku functionality that we are using.

`wakuUtils.js`

```javascript
import protons from "protons";
const proto = protons(`
    message SimpleChatMessage {
      uint64 timestamp = 1;
      string text = 2;
      string sender = 3;
    }
  `);

const selectFleetEnv = () => {
  // Works with react-scripts
  if (process?.env?.NODE_ENV === "development") {
    return ["fleets", "wakuv2.test", "waku-websocket"];
  } else {
    return ["fleets", "wakuv2.prod", "waku-websocket"];
  }
};

const processMsgs = (msg) => {
  if (!msg.payload) return;

  const { timestamp, text, sender } = proto.SimpleChatMessage.decode(
    msg.payload
  );

  const time = new Date(timestamp).toLocaleTimeString();

  const utf8Text = Buffer.from(text).toString("utf-8");

  return { timestamp: time, text: utf8Text, sender };
};

export { proto, selectFleetEnv, processMsgs };
```

Parts of code where we used waku in our live stream chats:

```javascript
// creating waku object
  useEffect(() => {
    if (!isLivestreamChat) return;
    if (!!waku) return;
    if (wakuStatus !== "None") return;

    setWakuStatus("Starting");

    // Create Waku
    Waku.create({
      libp2p: {
        config: {
          pubsub: {
            enabled: true,
            emitSelf: true,
          },
        },
      },
      bootstrap: getBootstrapNodes.bind({}, selectFleetEnv()),
    }).then((waku) => {
      setWaku(waku);
      setWakuStatus("Started");
      waku.waitForConnectedPeer().then(() => {
        setWakuStatus("Ready");
        console.log(wakuStatus);
      });
    });
    console.log(wakuStatus);
  }, [waku, wakuStatus]);

  const processWakuHistory = (retrievedMessages) => {
    const messages = retrievedMessages
      .map((msg) => processMsgs(msg))
      .filter(Boolean);

    setWakuMsgs((waku) => {
      return messages.concat(waku);
    });

    if (wakuMsgs.length >= 20) return true;
  };

  // fetching history of chats from waku-store
  useEffect(() => {
    if (wakuStatus !== "Ready") return;

    waku.store
      .queryHistory([ContentTopic], { callback: processWakuHistory })
      .catch((e) => {
        console.log("Failed to retrieve messages", e);
      });
    dispatch(setWakuStoreRetrieved(true));
  }, [waku, wakuStatus]);

  // sending message using waku-relay
  const handleWakuMessage = async (msgInput) => {
    if (!isLivestreamChat) return;
    if (wakuStatus !== "Ready") return;
    if (!msgInput) return;

    const text = msgInput.trim();

    const payload = proto.SimpleChatMessage.encode({
      timestamp: new Date(),
      text: text,
      sender:
        localStorage.getItem("livestream_viewer") ||
        window.ethereum.selectedAddress,
    });

    WakuMessage.fromBytes(payload, ContentTopic).then((wakuMessage) =>
      waku.relay.send(wakuMessage)
    );
    console.log(payload);
  };

  // observer for receiving messages
  const processIncomingMessage = useCallback((wakuMessage) => {
    const message = processMsgs(wakuMessage);
    setWakuMsgs((messages) => {
      return messages.concat(message);
    });
  }, []);

  // receive message using waku-relay
  useEffect(() => {
    if (!waku) return;

    waku.relay.addObserver(processIncomingMessage, [ContentTopic]);

    return function cleanUp() {
      waku.relay.deleteObserver(processIncomingMessage, [ContentTopic]);
    };
  }, [waku, wakuStatus, processIncomingMessage]);
```

## Notes

- js-waku version: 0.14.2

**Comment by D4nte** [comment]
1. Are you able to create a minimum, reproducible example?
2. The error show seem to be for react prod build, does the error happen for a dev build too? If so, what is the error? A dev build should help pinpoint the exact line that is an issue.

**Comment by ritvij14** [comment]
1. Yes we can reproduce it.
2. No it only breaks on prod, when we try to serve the prod build.

**Comment by D4nte** [comment]
1. Great, please publish the minimal, reproducible example so I can further investigate.

**Comment by D4nte** [comment]
FYI, this is what i am referring to https://stackoverflow.com/help/minimal-reproducible-example

**Comment by D4nte** [comment]
Bug also occurs with chat demo: https://status-im.github.io/js-waku/

**Comment by D4nte** [comment]
Leads:
- https://github.com/seanjameshan/starknet.js/issues/37#issuecomment-955797303
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility
- https://github.com/blockstack/stacks.js/issues/1096#issuecomment-946350299

**Comment by D4nte** [comment]
I was able to reproduce in the web-chat example by setting the `browsers.list.development` property of `package.json` to the same value than `browserslist.production`:

```json
    "development": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ]
```

and deleting the cache: `rm -rf node_modules/.cache`

**Comment by D4nte** [comment]
I was able to solve the issue in development with:

```
    "development": [
      ">0.2%",
      "not ie <= 99",
      "not android <= 4.4.4",
      "not dead",
      "not op_mini all"
    ]
```

Will apply to prod and see if it works in GH pages.

**Comment by D4nte** [comment]
Here is the upstream issue: https://github.com/paulmillr/noble-ed25519/issues/23

**Comment by D4nte** [comment]
```
▶ npm ls @noble/ed25519
js-waku@0.14.2 /home/froyer/src/status-im/js-waku
├─┬ @chainsafe/libp2p-noise@5.0.0
│ └─┬ peer-id@0.16.0
│   └─┬ libp2p-crypto@0.21.0
│     └── @noble/ed25519@1.3.3
└─┬ libp2p-gossipsub@0.12.1
  └─┬ libp2p-interfaces@2.0.6
    └─┬ libp2p-crypto@0.21.0
      └── @noble/ed25519@1.3.3 deduped
```

**Comment by D4nte** [comment]
Unfortunately, setting the following in the `package.json` of web-chat did not fix it in GH pages. Not sure if it's an issue with some caching:

```json
"browserslist": { 
   "development": [
      ">0.2%",
      "not ie <= 99",
      "not android <= 4.4.4",
      "not dead",
      "not op_mini all"
    ]
}
```

@ritvij14 can you try this solution with your project and let me know if it helps?

**Comment by ritvij14** [comment]
@D4nte yes ok let me try this on our system today, I will get back to you on this soon.

**Comment by D4nte** [comment]
> @D4nte yes ok let me try this on our system today, I will get back to you on this soon.

Great. Be sure to delete your `node_modules` to be sure it does not use the cache.

**Comment by ritvij14** [comment]
> Unfortunately, setting the following in the package.json of web-chat did not fix it in GH pages. Not sure if it's an issue with some caching, I need to investigate further.
> "browserslist": { 
   "development": [
      ">0.2%",
      "not ie <= 99",
      "not android <= 4.4.4",
      "not dead",
      "not op_mini all"
    ]
}
@ritvij14 can you try this solution with your project and let me know if it helps?

@D4nte I added this thing like this:
```
"production": [
      ">0.2%",
      "not ie <= 99",
      "not android <= 4.4.4",
      "not dead",
      "not op_mini all"
    ],
```

and on doing `yarn build && npx serve -s build`, it ran without problems. But I am still kind of confused as to how did doing this help.

**Comment by D4nte** [comment]
@ritvij14 please have a look at at what `browserslist` does. My understanding is that it set the browser target for which the code is transpiled to.
`">0.2%"` for example means: transpile code from browser that has a market share of more than 0.2% (I think).

This included all browsers that do not support BigInt such as ie 98 and below and android 4.4.3 and below.
Which mean the transpiled code did not contain definition of BigInt. Hence the error.

By restricting the browser target to more recent browser, it allowed the use of `BigInt`.

Keeping this issue open to track documentation effort.

**Comment by D4nte** [comment]
Documented in the ReactJS doc: https://github.com/vacp2p/docs.dappconnect.dev/pull/19
Also this issue can serve as documentation.

**Comment by mathieug-minogames** [comment]
So what's the fix? I see a scattering of messages with nothing definitive. I get the issue with production react builds.

**Comment by matbee-eth** [comment]
So what's the fix? I see a scattering of messages with nothing definitive. I get the issue with production react builds.

**Comment by ritvij14** [comment]
> > Unfortunately, setting the following in the package.json of web-chat did not fix it in GH pages. Not sure if it's an issue with some caching, I need to investigate further.
> > "browserslist": {
> > "development": [
> > ">0.2%",
> > "not ie <= 99",
> > "not android <= 4.4.4",
> > "not dead",
> > "not op_mini all"
> > ]
> > }
> > @ritvij14 can you try this solution with your project and let me know if it helps?
> 
> @D4nte I added this thing like this:
> 
> ```
> "production": [
>       ">0.2%",
>       "not ie <= 99",
>       "not android <= 4.4.4",
>       "not dead",
>       "not op_mini all"
>     ],
> ```
> 
> and on doing `yarn build && npx serve -s build`, it ran without problems. But I am still kind of confused as to how did doing this help.

@matbee-eth this is what you need to do. Add this in `package.json`

**Comment by Joshua-alt** [comment]
@D4nte 
your fix just saved my day,thank

**Comment by Shashank729** [comment]
I wasted 2 days on trying to fix it, tried everything from package update to cache clean. Nothing worked. Then saw this and implemented it and now it works. Thank you so much for saving my day! 

Thanks a ton!

**Comment by fryorcraken** [comment]
Hi, really sorry to hear you wasted time on this issue. Are you using `@waku/core` or `js-waku` npm packages? `js-waku` is now deprecated.
