### ISSUE TITLE
Connect web chat app to nim-waku test fleet via go-waku

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#45]
## Problem

js-libp2p only support websocket transport in the browser and nim-libp2p [does not yet support websocket](https://github.com/status-im/nim-libp2p/issues/407).
Which means that it is currently not possible to connect a browser chat app to the fleet.

## Solution

- go-libp2p supports websocket transport.
- go-waku supports both wakuv2 relay and store protocol (both as querying and queried nodes).

As a temporary solution, we could deploy a go-waku node in the fleet that also stores messages. This could be the goto node for the browser chat app

## Steps

- [x] Check that js-waku can connect to go-waku via websocket
- [x] Deploy a go-waku node behing nginx to server wss
- [ ] Ensure it connects to nim-waku test fleet and with the same history (blocked by https://github.com/status-im/go-waku/issues/22)
- [x] Point web chat app to go-waku instance #98

**Comment by D4nte** [comment]
@richard-ramos what is the multiaddress of a go-waku node instance I could use? I also need the peerId. Cheers!

**Comment by richard-ramos** [comment]
/ip4/134.209.113.86/tcp/9000/ws/
The peer id is 16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1

**Comment by D4nte** [comment]
Alright, it does not seem to work out of the box. More investigation needed

```
▶ npm run chat -- --staticNode /ip4/134.209.113.86/tcp/9000/ws/p2p/16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1

> js-waku@1.0.0 chat
> ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.113.86/tcp/9000/ws/p2p/16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1"

PeerId:  QmcMUayrWXjQxuJbE91EHto9guT4EMf87WYi4oJA8p8Xma
Listening on 
	- /ip4/127.0.0.1/tcp/46843
	- /ip4/192.168.178.251/tcp/46843
	- /ip4/10.20.0.5/tcp/46843
Please choose a nickname: franck
Hi, franck!
Dialing /ip4/134.209.113.86/tcp/9000/ws/p2p/16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1

/home/froyer/src/status-im/js-waku/node_modules/p-some/index.js:31
			reject(new AggregateError(errors));
          ^
AggregateError: 
    Error: Parse Error: Expected HTTP/
        at Socket.socketOnData (node:_http_client:502:22)
        at Socket.emit (node:events:378:20)
        at Socket.EventEmitter.emit (node:domain:470:12)
        at addChunk (node:internal/streams/readable:313:12)
        at readableAddChunk (node:internal/streams/readable:288:9)
        at Socket.Readable.push (node:internal/streams/readable:227:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at maybeSettle (/home/froyer/src/status-im/js-waku/node_modules/p-some/index.js:31:11)
    at /home/froyer/src/status-im/js-waku/node_modules/p-some/index.js:69:23
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
npm ERR! code 1
npm ERR! path /home/froyer/src/status-im/js-waku
npm ERR! command failed
npm ERR! command sh -c ts-node src/chat/index.ts "--staticNode" "/ip4/134.209.113.86/tcp/9000/ws/p2p/16Uiu2HAmVVi6Q4j7MAKVibquW8aA27UNrA4Q8Wkz9EetGViu8ZF1"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/froyer/.npm/_logs/2021-04-21T00_27_51_520Z-debug.log
```

**Comment by D4nte** [comment]
After further review, we need secure websocket support too (`wss`) to make the most out of a cluster deployment of go-waku.
We are currently tracking that in https://github.com/status-im/go-waku/issues/21.
Until this is done, then the cluster deployment would not be that useful and if it cannot be done in go then the deployment would involve using a webserver for the TLS layer.

Closing this until `wss` is resolved.

**Comment by D4nte** [comment]
Description updated: blocked by https://github.com/status-im/go-waku/issues/22

**Comment by D4nte** [comment]
Dropped, using `websockify` instead as per #107.
Connectivity sorted with #115.
