### ISSUE TITLE
Update docs to reflect breaking change in v0.16.0

### ISSUE THREAD

**Issue by jemboh** [status-im/js-waku#511]
## Problem

There was a breaking change introduced in [v0.16.0](https://github.com/status-im/js-waku/releases/tag/v0.16.0) where the `waitForConnectedPeer` function was replaced with `waitForRemotePeer`. The example code has been updated but not the documentation.

## Solution

Update the documentation to reflect this new change.

## Notes

- js-waku version: v0.16.0

**Comment by D4nte** [comment]
Fixed with #35
