### ISSUE TITLE
[spike] Prioritize caveats for browser usage

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#527]
## Problem

See #337.

There a number of actions to be taken to resolve #337. Some action may be low efforts. Other actions may lead to do upstream changes in dependencies.

It is uncertain what items should be prioritized.

### Goals

1. Make it more accessible
2.  Make it performant

### Outline

Analyze js-waku and its dependencies to prioritize the work, find the low hanging fruits and most bang for buck actions.

- What actions would reduce the bundle size the most?
- Which polyfill is the easiest to remove?
- Which polyfill removal would also assist with bundle size reduction or installation reduction? (as I don't think polyfills are bundled)
- Which are the biggest dependencies? Do themselves have an intelligent bundling strategy? Do they import too much? e.g. node-forge and libp2p libs

## Definition of Done

Non exhaustive:
- [ ] List dependencies by size
- [ ] List which dependencies requires a polyfill. Do they bring the polyfill or do they bring a dependency with a polyfill itself?
- [ ] Check if `test_utils` is bundled (should not be)
- [ ] List polyfill sizes
- [ ] Can we shim polyfills?
- [ ] Propose action plan, write it in #337

**Comment by D4nte** [comment]
Note that it may be useful to bundle the polyfills. This would improve UX and also make it easier to measure their size and get clear metrics.

**Comment by D4nte** [comment]
Consider https://github.com/Richienb/node-polyfill-webpack-plugin to remove having to setup polyfills

**Comment by fryorcraken** [comment]
Polyfills have been removed, this spike is not needed anymore. continue to track the work with #337
