### ISSUE TITLE
Change examples to use npmjs rather than file

### ISSUE THREAD

**Issue by jemboh** [status-im/js-waku#550]
Currently, we use `"file:../../build/*****",` in the `package.json` to reference `js-waku` in the root.

We should be using the published library on npm instead for consistency so it's the same as our users.

- [x] eth-pm
- [x] eth-pm-wallet-encryption
- [x] relay-angular-chat ( remove "@types/bl": "^5.0.2",)
- [x] relay-reactjs-chat
- [x] store-reactjs-chat
- [x] unpkg-js-store
- [x] web-chat

## Definition of Done

- [ ] All the examples using the published npmjs js-waku library

**Comment by D4nte** [comment]
Done with #605
