### ISSUE TITLE
Use utils from ethereum-cryptography package

### ISSUE THREAD

**Issue by prichodko** [status-im/js-waku#558]
As a part of the process of migrating from Node builtins, I would move to use utilities, like `hexToBytes`, `bytesToHex` from the [ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) package.

As you can see in the [implementation](https://github.com/paulmillr/noble-hashes/blob/main/src/utils.ts#L32), they don't rely on the `Buffer` builtin.

**Comment by D4nte** [comment]
Thanks @prichodko. Could you please clarify the gain of using implementations from `ethereum-cryptography` over the current implementation? I am not sure we want to add a new dependency.

**Comment by prichodko** [comment]
Current implementation indirectly forces users to depend on a Buffer polyfill and essentially add [2000 lines / 26kB of code](https://github.com/feross/buffer/blob/master/index.js). The proposed solution suggests only using what is needed for the package to work.

The package seems to be tree-shakeable, therefore allowing bundlers to pull only the imported code and not the whole package. However, there may be other parts depending on the `Buffer`, which would need the refactoring as well.

**Comment by prichodko** [comment]
Do you know, if any `js-waku` dependencies need `Buffer` polyfill?

**Comment by D4nte** [comment]
> Do you know, if any `js-waku` dependencies need `Buffer` polyfill?

This will be answered as part of #527 

> Current implementation indirectly forces users to depend on a Buffer polyfill and essentially adds [2000 lines / 26kB of code](https://github.com/feross/buffer/blob/master/index.js?rgh-link-date=2022-02-22T11%3A05%3A40Z). The proposed solution suggests only using what is needed for the package to work.

`hextToBytes` and `bytesToHex` do not use Buffer:

https://github.com/status-im/js-waku/blob/c1c1858175940264845721bb8db24ae19b281e10/src/lib/utils.ts#L19

I think you are referring to `hexToBuf` and `bufToHex` who already are on their way out.

**Comment by D4nte** [comment]
The worry here is the usage of the Buffer polyfill, this is resolved with #726.

Note that `ts-proto` uses `Buffer`: tracked with #335.
Some dependencies are using buffer: Will review as part of #527
