### ISSUE TITLE
can't retrieve encrypted messages

### ISSUE THREAD

**Issue by youdianku** [status-im/js-waku#724]
Use generateSymmetricKey for secure key generation encrypt a message, but waku.store.queryHistory it doesn't return encrypted message.

**Comment by D4nte** [comment]
Hi @youdianku, 

Please confirm you read https://docs.wakuconnect.dev/docs/guides/04_encrypt_messages_version_1/ 

If so, can you please share some code?

**Comment by youdianku** [comment]
i have found the problem in the code, thanks for your reply @D4nte
