### ISSUE TITLE
queryHistory

### ISSUE THREAD

**Issue by poplar-sea** [status-im/js-waku#809]
This is a support request

## Problem
When I use queryHistory to query the history, I found that it can only be found on the day, and it will be lost after 0:00, and the history is empty
`waku.store
            .queryHistory([contentTopic], {
              callback,
              pageSize: 100,
              timeFilter: {
                startTime:new Date().setTime(Date.now() - 1000 * 60 * 60 * 24 * 7),
                endTime:new Date()
              },
              decryptionKeys:[Key]
            })`

- js-waku version:0.24.0
- Environment (browser software and version, system software and version):Chrome 103.0.5060.53

**Comment by D4nte** [comment]
Can you please clarify how you create your Waku node, especially regarding the bootstrap method.
Some logs would also be helpful to check what peer is used for the store query.

Note that if you use the Status test fleet than this behaviour is expected.

**Comment by poplar-sea** [comment]
This is the code that I created the  WaKunode
` Waku.create({ 
            bootstrap: {peers:['/dns4/node-01.do-ams3.wakuv2.prod.statusim.net/tcp/443/wss/p2p/16Uiu2HAmL5okWopX7NqZWBUKVqW8iUxCEmd5GMHLVPwCgzYzQv3e']},
            pingKeepAlive:10
        })`

**Comment by D4nte** [comment]
@jm-clius Is there a regular clean up of the prod DB happening?

**Comment by poplar-sea** [comment]
> 
no, i haven't.

**Comment by jm-clius** [comment]
`wakuv2.prod` only keeps about 10000 messages of history. Depending on message rates, this translates to roughly a couple of hours' worth of historical messages. We have a beta version of the store protocol out that can keep up to 30 days of history (or even longer), but it's not yet deployed to the `wakuv2.prod` fleet while it's being dogfooded and query performance is improved: https://github.com/status-im/nwaku/issues/1024

**Comment by poplar-sea** [comment]
> `wakuv2.prod` only keeps about 10000 messages of history. Depending on message rates, this translates to roughly a couple of hours' worth of historical messages. We have a beta version of the store protocol out that can keep up to 30 days of history (or even longer), but it's not yet deployed to the `wakuv2.prod` fleet while it's being dogfooded and query performance is improved: [status-im/nwaku#1024](https://github.com/status-im/nwaku/issues/1024)

I have a question: is 10000 messages of history shared by all projects using waku ?

**Comment by D4nte** [comment]
> I have a question: is 10000 messages of history shared by all projects using waku ?

Yes, it is across all projects.
Do note that we are doing major performance improvement on the nwaku store implementations, you can track here: https://github.com/status-im/nwaku/issues/1024

@jm-clius can you comment on the impact this may have regarding number of messages a nwaku node can store?

**Comment by jm-clius** [comment]
@D4nte @poplar-sea, since the improvements will allow messages to be stored for a specific time period, the number of messages stored will depend on the message rate. For 30 days this could roughly equate to ~2 million messages or more.

Note that it is possible to configure a store to store history for only a single (or subset of) projects, but we do not configure `wakuv2.prod` this way.
