### ISSUE TITLE
Generate random nick

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#81]
Generate a random nick when starting the web app so that users can differentiate themselves from other without having to use the `/nick` command

**Comment by littlealex003** [comment]
hi this is done; doesn't look like i can use the agile board but i submit a pull request

**Comment by littlealex003** [comment]
https://github.com/status-im/js-waku/pull/94

**Comment by D4nte** [comment]
You can use GitHub keywords by writing "Resolves #81" in the PR's description.
