### ISSUE TITLE
Improve chat line rendering

### ISSUE THREAD

**Issue by D4nte** [status-im/js-waku#86]
## Problem

`Card` is used for chat line rendering:

https://github.com/status-im/js-waku/blob/72c9bef3d2c171e16689e4c9d66364f33d110ad6/web-chat/src/ChatList.tsx#L49

This is not great as the messages' height are just too big. It's using more vertical space than needed

Edit: We will dog food the app to replace the current \#waku discord channel. The channel can get very busy, especially overnight. Hence, the theme needs to be a la discord/slack/element.

## Definition of Done

Have a rendering similar to what is currently done and most modern chat apps:

- login and date on top left corner
- login in small case
- date in smaller case than login
- message in standard/normal case left aligned

**Comment by littlealex003** [comment]
Hi,

Do you want a custom React component in HTML or to leverage something existing? I'm sure there's an existing chat component that could be stylized.

**Comment by littlealex003** [comment]
Looks like you are using material-ui

**Comment by D4nte** [comment]
Yes, currently using material-ui.

The aim of the web app is to show case js-waku (see #67). Hence it is best if we use pre-made libraries to not clutter the code.

We expect developers to have a look at the code to see how they can leverage js-waku lib so we should take their attention away from that by re-inventing the wheel :)

**Comment by littlealex003** [comment]
Great, sounds like we are on the same page; I would suggest we find a pre-built React Material template view we like and plug the js-waku functionality in, I will find something now

**Comment by littlealex003** [comment]
i guess it depends on how complicated an interface we want; if it's just the simple single room, this is overkill but: http://chatvia-dark.react.themesbrand.com/dashboard is a complete solution idea; https://developers.livechat.com/docs/react-chat-ui-kit/ may be a better solution for our needs at the moment though, it looks perfect for what you want to accomplish here

**Comment by littlealex003** [comment]
I get started on refactoring to this https://developers.livechat.com/docs/react-chat-ui-kit/ and let's see how it looks

**Comment by D4nte** [comment]
Ok that's cool, I didn't know this existed.

I imagined more of a Discord/Slack look. I wonder how chatvia look when there are more than 2 participants in a conversation?

**Comment by littlealex003** [comment]
I think there are a million things out there, designers crank this stuff out for their portfolios etc.

The final look and feel can be customized using the style sheets, but ideally we start with something that looks like we want it to.

I must admit I use Telegram and Signal as much as Discord or Slack, but of course I have used many things over the years (and usually am using 5 at once these days).

It's easy to change, most important is that the functionality is just plugged into the UI. We could even have multiple versions.

**Comment by littlealex003** [comment]
This is good to go; I played around with a couple possibilities and we can tweak the CSS, but I think this is a clean utilization of the existing toolkit.

**Comment by D4nte** [comment]
Please note that the problem description is:

> This is not great as the messages' height are just too big. It's using more vertical space than needed

Which means that using a bubble theme a la whatasapp/messenger/signal does not solve this issue.

**Comment by littlealex003** [comment]
Ah OK fair enough, sorry. I thought the idea was to clutter the code as
little as possible by using stuff off the shelf; as I mentioned we can
tweak the CSS on this UI as well to make it smaller, this is how it looks
out of the box.

The Bubble is easily turned off by removing the <Bubble> tag.

If the idea is to Dogfood this then tweaking it to be smaller makes sense
indeed, I thought the idea was just an example for integration.

**Comment by D4nte** [comment]
Please see my comments in the PR :)

**Comment by littlealex003** [comment]
Sure, will do, just going through my email or I don't see them all :)

**Comment by littlealex003** [comment]
OK, I reduced the padding to make this much more space efficient and grouped the sequential lines by sender together, take a look when you have a chance; can certainly make it look better but I think this is the start of what you had in mind.

**Comment by littlealex003** [comment]
Here's another more full featured chat interface out there: https://www.pubnub.com/chat-ui-kit/

This is good for now for our simple app but if we want something more full featured we can look around
